### PR TITLE
Implement alt-link and bind it to ^o

### PR DESCRIPTION
**Pull request by lyricnz**
Add support for an "alternate link" for a coin, to a user-defined target.  This is expressed in a code snippet, defined in the config.toml file. The code has access to `sprintf` and a `coin` object with [ID, Name, Symbol, Rank, Slug] available.

```
alt_link_code = "sprintf(\"https://www.tradingview.com/chart/?symbol=%sUSDT\", coin.Symbol)"
```

Per #283

### CODE REVIEW

**Comment by lyricnz** [comment]
Thoughts:
- signature of interface.CoinLink() and interface.AltCoinLink() are different - they should probably be the same
- in fact, CoinLink should probably just be a pre-configured example of the same pattern
- in fact, we could probably support an arbitrary number of CoinLinks (though managing config would be a pain)
- the config should probably be in an api-specific section, but updating config structs gives me a headache

**Comment by lyricnz** [comment]
The config is a little codey.  Might be easier to explain with simple tokens.

**Comment by miguelmota** [comment]
(copying my comment from discord):

This format makes it very specific to Go but the config file should be generalized. I think something like `alt_link_code = "https://www.tradingview.com/chart/?symbol=:SYMBOL:"` would be better and we can offer `:SYMBOL:`, `:NAME`, `:ID:` , etc as variables

**Comment by miguelmota** [comment]
Merging this with some updates

Example

```toml
alt_coin_link = "https://www.tradingview.com/symbols/{{SYMBOL}}USD/"
```

Available tags:
- `{{ID}}`
- `{{NAME}}`
- `{{RANK}}`
- `{{SLUG}}`
- `{{SYMBOL}}`

**Pull request merged**
